---
- name: Create and maintain EE pod for troubleshooting
  hosts: localhost
  gather_facts: false

  vars:
    ee_image: "infraengco/andrew-ansible-ee:latest"  # Replace with your EE image and tag
    pod_name: "ee-troubleshoot-pod"
    namespace: "awx"
    kubeconfig_path: "/root/.kube/config"  # Specify your kubeconfig path

  tasks:
    - name: Create EE pod
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: "{{ pod_name }}"
            namespace: "{{ namespace }}"
          spec:
            containers:
              - name: ee-container
                image: "{{ ee_image }}"
                command: ["/bin/sh", "-c", "while true; do sleep 86400; done"]
      register: pod_result

    - name: Wait for pod to be ready
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        kind: Pod
        namespace: "{{ namespace }}"
        name: "{{ pod_name }}"
      register: pod_info
      until: pod_info.resources[0].status.phase == "Running"
      retries: 10
      delay: 30

    - name: Display pod information
      ansible.builtin.debug:
        msg:
          - "Pod Name: {{ pod_name }}"
          - "Namespace: {{ namespace }}"
          - "Pod IP: {{ pod_info.resources[0].status.podIP }}"
          - "Node: {{ pod_info.resources[0].spec.nodeName }}"

    - name: Provide instructions
      ansible.builtin.debug:
        msg:
          - "The EE pod is now running and will stay online indefinitely."
          - "You can access it using:"
          - "kubectl exec -it {{ pod_name }} -n {{ namespace }} -- /bin/sh"
          - "Remember to delete the pod when you're done:"
          - "kubectl delete pod {{ pod_name }} -n {{ namespace }}"
