---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: awx.awx
      - name: community.vmware
      - name: cisco.nxos
      - name: cisco.aci
      - name: kubernetes.core
      - name: ansible.posix
      - name: ansible.windows
      - name: redhatinsights.insights
  python:
    - paramiko
    - pymssql
    - git+https://github.com/vmware/vsphere-automation-sdk-python.git
  system:
    - dnf-plugins-core
    - git
    - python3-devel
    - gcc
    - iputils

additional_build_steps:
  prepend_base:
    - RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - RUN rm kubectl
  append_final:
    - RUN pip install --upgrade pip
    
options:
  package_manager_path: /usr/bin/dnf