---
- name: Pre Migration Ping Test
  hosts: localhost
  gather_facts: false
  vars:
    ping_name: pre
  tasks:
    - name: Debug all variables
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
  roles:
    - ping_test

- name: Build dynamic inventory of interfaces to migrate
  hosts: localhost
  gather_facts: false
  roles:
    - build_inventory

- name: Execute migrate task based on inventory result from API call
  hosts: data_inventory
  connection: local
  serial: 1
  gather_facts: false
  roles:
    - migrate_server

- name: After Migration Ping Test
  hosts: localhost
  gather_facts: false
  vars:
    ping_name: post
  roles:
    - ping_test

- name: Set post Migration Ping Var
  hosts: localhost
  gather_facts: false
  roles:
    - set_migration_vars

- name: Post server info to ServiceNow
  hosts: localhost
  gather_facts: false
  roles:
    - post_to_servicenow
