---
- name: Ping Localhost and 127.0.0.1
  hosts: localhost
  gather_facts: false

  tasks:
  # Networking tasks
    - name: Check network interfaces
      ansible.builtin.command:
        cmd: ifconfig
      register: ifconfig_result

    - name: Display network interfaces
      ansible.builtin.debug:
        var: ifconfig_result.stdout_lines

    - name: Check routing table
      ansible.builtin.command:
        cmd: route -n
      register: route_result

    - name: Display routing table
      ansible.builtin.debug:
        var: route_result.stdout_lines

# PING tasks
    - name: Check ping permissions
      ansible.builtin.command:
        cmd: ls -l /usr/sbin/ping
      register: ping_permissions

    - name: Display ping permissions
      ansible.builtin.debug:
        var: ping_permissions.stdout
    
    - name: Show the location of the ping command using 'command -v'
      ansible.builtin.command:
        cmd: command -v ping
      register: command_v_ping_result

    - name: Display the location of the ping command using 'command -v'
      ansible.builtin.debug:
        var: command_v_ping_result.stdout

    - name: Show the location of the ping command using 'type'
      ansible.builtin.shell:
        cmd: type ping
      register: type_ping_result

    - name: Display the location of the ping command using 'type'
      ansible.builtin.debug:
        var: type_ping_result.stdout

    - name: Ping 127.0.0.1
      ansible.builtin.command:
        cmd: ping -c 2 127.0.0.1
      register: ping_result

    - name: Display ping result
      ansible.builtin.debug:
        var: ping_result.stdout

