- name: Show Ping Test before Post
  ansible.builtin.debug:
    msg:
      - "{{ server_var.ticket_url }}"

# Initialize formatted_network_details
- name: Initialize formatted network details variable
  ansible.builtin.set_fact:
    formatted_network_details: []

# Setup formatted_network_details and associated data
- name: Extract and format network details
  ansible.builtin.set_fact:
    formatted_network_details: >-
      {{
        formatted_network_details + [
          'Name: ' + (item.name | default('N/A')) +
          ' | Port: ' + (item.port | default([])) +
          ' | Switch: ' + (item.switch | default([]))
        ]
      }}
  loop: "{{ server_var.networks | default([]) }}"

- name: Debug server_var
  ansible.builtin.debug:
    var: server_var

- name: Debug formatted_network_details
  ansible.builtin.debug:
    var: formatted_network_details

- name: Debug error_message before sending to SNOW
  ansible.builtin.debug:
    var: server_var

# Add source and destination network details
- name: Set network details for ServiceNow
  ansible.builtin.set_fact:
    snow_data: >-
      {{
        {
          "server_name": server_var.server_name,
          "source_network": server_var.snow_network_details.source_network,
          "destination_network": server_var.snow_network_details.destination_network,
          "network_details": formatted_network_details
        }
      }}

- name: Debug network details for SNOW
  ansible.builtin.debug:
    var: snow_data

# Send structured data to SNOW using uri module
- name: Send data to ServiceNow
  ansible.builtin.uri:
    url: "{{ snow_data.ticket_url }}"
    method: POST
    body: "{{ snow_data | to_json }}"
    # url_username: "{{ snow_username }}"
    # url_password: "{{ snow_password }}"
    body_format: json
    headers:
      Content-Type: "application/json"
    validate_certs: false
  when: snow_data.ticket_url is defined and snow_data.ticket_url | length > 0
  register: snow_response

- name: Debug SNOW response
  ansible.builtin.debug:
    var: snow_response
