# roles/ping_test/tasks/main.yml

- name: Debug vars
  ansible.builtin.debug:
    var: server_name

- name: Printing Server (debug)
  ansible.builtin.debug:
    msg: "Pinging server: {{ server_name }}"

- name: Ping Server
  ansible.builtin.command:
    cmd: ping -c 4 {{ server_name }}
  register: ping_result

- name: Save Ping Test Results as Artifacts
  ansible.builtin.copy:
    content: "{{ ping_result.stdout }}"
    dest: "/tmp/ping_{{ ping_name }}_{{ server_name }}.log"
    mode: '0644'
