---
- name: Printing Server (debug)
  ansible.builtin.debug:
    msg: "Pinging {{ server_name }}"
  when: ping_test_server_name is defined

- name: Check if ping command exists using type
  ansible.builtin.command:
    cmd: type ping
  register: ping_check
  failed_when: ping_check.rc != 0
  changed_when: false

- name: Show ping command path
  ansible.builtin.debug:
    msg: "Ping command path: {{ ping_check.stdout }}"

- name: Display environment variables
  ansible.builtin.shell: env
  register: env_vars
  changed_when: false

- name: Show environment variables
  ansible.builtin.debug:
    var: env_vars.stdout_lines

- name: Ping Server using absolute path
  ansible.builtin.shell: |
    /usr/sbin/ping -c2 "{{ server_name }}"
  register: router_ping
  failed_when: router_ping.rc != 0
  changed_when: false
  ignore_errors: true

- name: Save Ping Test Results as Artifacts
  ansible.builtin.set_stats:
    data:
      ping_test_results: "{{ router_ping.stdout_lines }}"
    per_host: false

- name: Save Pre Ping Test Results as Variable
  ansible.builtin.set_fact:
    pre_ping_test_results_var: "{{ router_ping.stdout_lines }}"
  when: ping_name == "pre"

- name: Save Post Ping Test Results as Variable
  ansible.builtin.set_fact:
    post_ping_test_results_var: "{{ router_ping.stdout_lines }}"
  when: ping_name == "post"

- name: Show Ping Test Results
  ansible.builtin.debug:
    msg: "{{ router_ping.stdout_lines }}"
